//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WindowsPhoneTestFramework.Client.AutomationClient.Remote {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandBase", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.LookForTypeCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ControlContainsImageCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetCheckedStatusCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ScrollIntoViewCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetApplicationSettingsCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetApplicationSettingsCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.LookForAppBarItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.NavigateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SelectorItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetProgressCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.InvokeAppBarTapCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetApplicationSettingCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.PivotCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetApplicationSettingCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetColorCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ListBoxItemScrollIntoViewCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ListBoxItemSelectCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ScrollCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetIsEnabledCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetValueCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetValueCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GenericCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetPositionCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetTextCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.InvokeControlTapActionCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetFocusCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetTextCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.TakePictureCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ToggleButtonCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.BackgroundAudioCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ConfirmAliveCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetPerformanceCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.LookForTextCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.NullCommand))]
    public partial class CommandBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid IdField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookForTypeCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController")]
    public partial class LookForTypeCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
        
        private string TypeStrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeStr {
            get {
                return this.TypeStrField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeStrField, value) != true)) {
                    this.TypeStrField = value;
                    this.RaisePropertyChanged("TypeStr");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomationElementCommandBase", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ControlContainsImageCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetCheckedStatusCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ScrollIntoViewCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetApplicationSettingsCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetApplicationSettingsCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.LookForAppBarItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.NavigateCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SelectorItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetProgressCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.InvokeAppBarTapCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetApplicationSettingCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.PivotCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetApplicationSettingCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetColorCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ListBoxItemScrollIntoViewCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ListBoxItemSelectCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ScrollCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetIsEnabledCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetValueCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetValueCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GenericCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetPositionCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.GetTextCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.InvokeControlTapActionCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetFocusCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SetTextCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.TakePictureCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ToggleButtonCommand))]
    public partial class AutomationElementCommandBase : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
        
        private WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationIdentifier AutomationIdentifierField;
        
        private int OrdinalField;
        
        private WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationIdentifier ParentIdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationIdentifier AutomationIdentifier {
            get {
                return this.AutomationIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomationIdentifierField, value) != true)) {
                    this.AutomationIdentifierField = value;
                    this.RaisePropertyChanged("AutomationIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ordinal {
            get {
                return this.OrdinalField;
            }
            set {
                if ((this.OrdinalField.Equals(value) != true)) {
                    this.OrdinalField = value;
                    this.RaisePropertyChanged("Ordinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationIdentifier ParentIdentifier {
            get {
                return this.ParentIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdentifierField, value) != true)) {
                    this.ParentIdentifierField = value;
                    this.RaisePropertyChanged("ParentIdentifier");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlContainsImageCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ControlContainsImageCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string ImageNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCheckedStatusCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetCheckedStatusCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScrollIntoViewCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ScrollIntoViewCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetApplicationSettingsCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SetApplicationSettingsCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private System.Collections.Generic.Dictionary<string, string> SettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Settings {
            get {
                return this.SettingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsField, value) != true)) {
                    this.SettingsField = value;
                    this.RaisePropertyChanged("Settings");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetApplicationSettingsCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetApplicationSettingsCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookForAppBarItemCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class LookForAppBarItemCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NavigateCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class NavigateCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string DirectionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectorItemCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SelectorItemCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private int IndexOfItemToSelectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IndexOfItemToSelect {
            get {
                return this.IndexOfItemToSelectField;
            }
            set {
                if ((this.IndexOfItemToSelectField.Equals(value) != true)) {
                    this.IndexOfItemToSelectField = value;
                    this.RaisePropertyChanged("IndexOfItemToSelect");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProgressCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetProgressCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private bool ReturnEmptyIfNotVisibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnEmptyIfNotVisible {
            get {
                return this.ReturnEmptyIfNotVisibleField;
            }
            set {
                if ((this.ReturnEmptyIfNotVisibleField.Equals(value) != true)) {
                    this.ReturnEmptyIfNotVisibleField = value;
                    this.RaisePropertyChanged("ReturnEmptyIfNotVisible");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvokeAppBarTapCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class InvokeAppBarTapCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetApplicationSettingCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetApplicationSettingCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string KeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PivotCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class PivotCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private bool PivotLastField;
        
        private string PivotNameField;
        
        private bool PivotNextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PivotLast {
            get {
                return this.PivotLastField;
            }
            set {
                if ((this.PivotLastField.Equals(value) != true)) {
                    this.PivotLastField = value;
                    this.RaisePropertyChanged("PivotLast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PivotName {
            get {
                return this.PivotNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PivotNameField, value) != true)) {
                    this.PivotNameField = value;
                    this.RaisePropertyChanged("PivotName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PivotNext {
            get {
                return this.PivotNextField;
            }
            set {
                if ((this.PivotNextField.Equals(value) != true)) {
                    this.PivotNextField = value;
                    this.RaisePropertyChanged("PivotNext");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetApplicationSettingCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SetApplicationSettingCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetColorCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetColorCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListBoxItemScrollIntoViewCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ListBoxItemScrollIntoViewCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListBoxItemSelectCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ListBoxItemSelectCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScrollCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ScrollCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private int HorizontalScrollField;
        
        private int VerticalScrollField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HorizontalScroll {
            get {
                return this.HorizontalScrollField;
            }
            set {
                if ((this.HorizontalScrollField.Equals(value) != true)) {
                    this.HorizontalScrollField = value;
                    this.RaisePropertyChanged("HorizontalScroll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VerticalScroll {
            get {
                return this.VerticalScrollField;
            }
            set {
                if ((this.VerticalScrollField.Equals(value) != true)) {
                    this.VerticalScrollField = value;
                    this.RaisePropertyChanged("VerticalScroll");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIsEnabledCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetIsEnabledCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetValueCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SetValueCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string TextValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextValue {
            get {
                return this.TextValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TextValueField, value) != true)) {
                    this.TextValueField = value;
                    this.RaisePropertyChanged("TextValue");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetValueCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetValueCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GenericCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string Parameter0Field;
        
        private string Parameter1Field;
        
        private string Parameter2Field;
        
        private string Parameter3Field;
        
        private string Parameter4Field;
        
        private string PleaseDoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter0 {
            get {
                return this.Parameter0Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter0Field, value) != true)) {
                    this.Parameter0Field = value;
                    this.RaisePropertyChanged("Parameter0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter1 {
            get {
                return this.Parameter1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter1Field, value) != true)) {
                    this.Parameter1Field = value;
                    this.RaisePropertyChanged("Parameter1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter2 {
            get {
                return this.Parameter2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter2Field, value) != true)) {
                    this.Parameter2Field = value;
                    this.RaisePropertyChanged("Parameter2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter3 {
            get {
                return this.Parameter3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter3Field, value) != true)) {
                    this.Parameter3Field = value;
                    this.RaisePropertyChanged("Parameter3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameter4 {
            get {
                return this.Parameter4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter4Field, value) != true)) {
                    this.Parameter4Field = value;
                    this.RaisePropertyChanged("Parameter4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PleaseDo {
            get {
                return this.PleaseDoField;
            }
            set {
                if ((object.ReferenceEquals(this.PleaseDoField, value) != true)) {
                    this.PleaseDoField = value;
                    this.RaisePropertyChanged("PleaseDo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPositionCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetPositionCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private bool ReturnEmptyIfNotVisibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnEmptyIfNotVisible {
            get {
                return this.ReturnEmptyIfNotVisibleField;
            }
            set {
                if ((this.ReturnEmptyIfNotVisibleField.Equals(value) != true)) {
                    this.ReturnEmptyIfNotVisibleField = value;
                    this.RaisePropertyChanged("ReturnEmptyIfNotVisible");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTextCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetTextCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvokeControlTapActionCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class InvokeControlTapActionCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetFocusCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SetFocusCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SetTextCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class SetTextCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TakePictureCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class TakePictureCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToggleButtonCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ToggleButtonCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.AutomationElementCommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackgroundAudioCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class BackgroundAudioCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
        
        private WindowsPhoneTestFramework.Client.AutomationClient.Remote.AudioInstruction CommandField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsPhoneTestFramework.Client.AutomationClient.Remote.AudioInstruction Command {
            get {
                return this.CommandField;
            }
            set {
                if ((this.CommandField.Equals(value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmAliveCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class ConfirmAliveCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPerformanceCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class GetPerformanceCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookForTextCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class LookForTextCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NullCommand", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public partial class NullCommand : WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutomationIdentifier", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Interfaces")]
    public partial class AutomationIdentifier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AutomationNameField;
        
        private string DisplayedTextField;
        
        private string ElementNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutomationName {
            get {
                return this.AutomationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AutomationNameField, value) != true)) {
                    this.AutomationNameField = value;
                    this.RaisePropertyChanged("AutomationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayedText {
            get {
                return this.DisplayedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayedTextField, value) != true)) {
                    this.DisplayedTextField = value;
                    this.RaisePropertyChanged("DisplayedText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElementName {
            get {
                return this.ElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementNameField, value) != true)) {
                    this.ElementNameField = value;
                    this.RaisePropertyChanged("ElementName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AudioInstruction", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Commands")]
    public enum AudioInstruction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stop = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBase", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.FailedResultBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ActionFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ExceptionFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.NotFoundFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.TimeoutFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.DictionaryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ProgressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.PictureResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.PositionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SuccessResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.SuccessResultColor))]
    public partial class ResultBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailedResultBase", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ActionFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ExceptionFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.NotFoundFailedResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WindowsPhoneTestFramework.Client.AutomationClient.Remote.TimeoutFailedResult))]
    public partial class FailedResultBase : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private string FailureTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureText {
            get {
                return this.FailureTextField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureTextField, value) != true)) {
                    this.FailureTextField = value;
                    this.RaisePropertyChanged("FailureText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionFailedResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class ActionFailedResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.FailedResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionFailedResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class ExceptionFailedResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.FailedResultBase {
        
        private string ExceptionMessageField;
        
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotFoundFailedResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class NotFoundFailedResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.FailedResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeoutFailedResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class TimeoutFailedResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.FailedResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictionaryResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class DictionaryResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private System.Collections.Generic.Dictionary<string, string> ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgressResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class ProgressResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private double CurrentField;
        
        private double MaxField;
        
        private double MinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Current {
            get {
                return this.CurrentField;
            }
            set {
                if ((this.CurrentField.Equals(value) != true)) {
                    this.CurrentField = value;
                    this.RaisePropertyChanged("Current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Max {
            get {
                return this.MaxField;
            }
            set {
                if ((this.MaxField.Equals(value) != true)) {
                    this.MaxField = value;
                    this.RaisePropertyChanged("Max");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Min {
            get {
                return this.MinField;
            }
            set {
                if ((this.MinField.Equals(value) != true)) {
                    this.MinField = value;
                    this.RaisePropertyChanged("Min");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PictureResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class PictureResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private string EncodedPictureBytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncodedPictureBytes {
            get {
                return this.EncodedPictureBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodedPictureBytesField, value) != true)) {
                    this.EncodedPictureBytesField = value;
                    this.RaisePropertyChanged("EncodedPictureBytes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class PositionResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private double HeightField;
        
        private double LeftField;
        
        private double TopField;
        
        private double WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuccessResult", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class SuccessResult : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private string ResultTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultText {
            get {
                return this.ResultTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTextField, value) != true)) {
                    this.ResultTextField = value;
                    this.RaisePropertyChanged("ResultText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuccessResultColor", Namespace="http://schemas.datacontract.org/2004/07/WindowsPhoneTestFramework.Server.WCFHoste" +
        "dAutomationController.Results")]
    public partial class SuccessResultColor : WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase {
        
        private string ResultColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultColor {
            get {
                return this.ResultColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultColorField, value) != true)) {
                    this.ResultColorField = value;
                    this.RaisePropertyChanged("ResultColor");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Remote.IPhoneAutomationService")]
    public interface IPhoneAutomationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAutomationService/GetNextCommand", ReplyAction="http://tempuri.org/IPhoneAutomationService/GetNextCommandResponse")]
        System.IAsyncResult BeginGetNextCommand(int timeoutInMilliseconds, System.AsyncCallback callback, object asyncState);
        
        WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase EndGetNextCommand(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAutomationService/ContinueProcessing", ReplyAction="http://tempuri.org/IPhoneAutomationService/ContinueProcessingResponse")]
        System.IAsyncResult BeginContinueProcessing(System.Guid commandId, System.AsyncCallback callback, object asyncState);
        
        bool EndContinueProcessing(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAutomationService/SubmitResult", ReplyAction="http://tempuri.org/IPhoneAutomationService/SubmitResultResponse")]
        System.IAsyncResult BeginSubmitResult(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result, System.AsyncCallback callback, object asyncState);
        
        void EndSubmitResult(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAutomationService/RawSubmitResult", ReplyAction="http://tempuri.org/IPhoneAutomationService/RawSubmitResultResponse")]
        System.IAsyncResult BeginRawSubmitResult(string jsonResult, System.AsyncCallback callback, object asyncState);
        
        bool EndRawSubmitResult(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneAutomationServiceChannel : WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNextCommandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNextCommandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContinueProcessingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ContinueProcessingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RawSubmitResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RawSubmitResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneAutomationServiceClient : System.ServiceModel.ClientBase<WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService>, WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService {
        
        private BeginOperationDelegate onBeginGetNextCommandDelegate;
        
        private EndOperationDelegate onEndGetNextCommandDelegate;
        
        private System.Threading.SendOrPostCallback onGetNextCommandCompletedDelegate;
        
        private BeginOperationDelegate onBeginContinueProcessingDelegate;
        
        private EndOperationDelegate onEndContinueProcessingDelegate;
        
        private System.Threading.SendOrPostCallback onContinueProcessingCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitResultDelegate;
        
        private EndOperationDelegate onEndSubmitResultDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitResultCompletedDelegate;
        
        private BeginOperationDelegate onBeginRawSubmitResultDelegate;
        
        private EndOperationDelegate onEndRawSubmitResultDelegate;
        
        private System.Threading.SendOrPostCallback onRawSubmitResultCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PhoneAutomationServiceClient() {
        }
        
        public PhoneAutomationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneAutomationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneAutomationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneAutomationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetNextCommandCompletedEventArgs> GetNextCommandCompleted;
        
        public event System.EventHandler<ContinueProcessingCompletedEventArgs> ContinueProcessingCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SubmitResultCompleted;
        
        public event System.EventHandler<RawSubmitResultCompletedEventArgs> RawSubmitResultCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.BeginGetNextCommand(int timeoutInMilliseconds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNextCommand(timeoutInMilliseconds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.EndGetNextCommand(System.IAsyncResult result) {
            return base.Channel.EndGetNextCommand(result);
        }
        
        private System.IAsyncResult OnBeginGetNextCommand(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int timeoutInMilliseconds = ((int)(inValues[0]));
            return ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).BeginGetNextCommand(timeoutInMilliseconds, callback, asyncState);
        }
        
        private object[] OnEndGetNextCommand(System.IAsyncResult result) {
            WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase retVal = ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).EndGetNextCommand(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNextCommandCompleted(object state) {
            if ((this.GetNextCommandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNextCommandCompleted(this, new GetNextCommandCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNextCommandAsync(int timeoutInMilliseconds) {
            this.GetNextCommandAsync(timeoutInMilliseconds, null);
        }
        
        public void GetNextCommandAsync(int timeoutInMilliseconds, object userState) {
            if ((this.onBeginGetNextCommandDelegate == null)) {
                this.onBeginGetNextCommandDelegate = new BeginOperationDelegate(this.OnBeginGetNextCommand);
            }
            if ((this.onEndGetNextCommandDelegate == null)) {
                this.onEndGetNextCommandDelegate = new EndOperationDelegate(this.OnEndGetNextCommand);
            }
            if ((this.onGetNextCommandCompletedDelegate == null)) {
                this.onGetNextCommandCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNextCommandCompleted);
            }
            base.InvokeAsync(this.onBeginGetNextCommandDelegate, new object[] {
                        timeoutInMilliseconds}, this.onEndGetNextCommandDelegate, this.onGetNextCommandCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.BeginContinueProcessing(System.Guid commandId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginContinueProcessing(commandId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.EndContinueProcessing(System.IAsyncResult result) {
            return base.Channel.EndContinueProcessing(result);
        }
        
        private System.IAsyncResult OnBeginContinueProcessing(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid commandId = ((System.Guid)(inValues[0]));
            return ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).BeginContinueProcessing(commandId, callback, asyncState);
        }
        
        private object[] OnEndContinueProcessing(System.IAsyncResult result) {
            bool retVal = ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).EndContinueProcessing(result);
            return new object[] {
                    retVal};
        }
        
        private void OnContinueProcessingCompleted(object state) {
            if ((this.ContinueProcessingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ContinueProcessingCompleted(this, new ContinueProcessingCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ContinueProcessingAsync(System.Guid commandId) {
            this.ContinueProcessingAsync(commandId, null);
        }
        
        public void ContinueProcessingAsync(System.Guid commandId, object userState) {
            if ((this.onBeginContinueProcessingDelegate == null)) {
                this.onBeginContinueProcessingDelegate = new BeginOperationDelegate(this.OnBeginContinueProcessing);
            }
            if ((this.onEndContinueProcessingDelegate == null)) {
                this.onEndContinueProcessingDelegate = new EndOperationDelegate(this.OnEndContinueProcessing);
            }
            if ((this.onContinueProcessingCompletedDelegate == null)) {
                this.onContinueProcessingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnContinueProcessingCompleted);
            }
            base.InvokeAsync(this.onBeginContinueProcessingDelegate, new object[] {
                        commandId}, this.onEndContinueProcessingDelegate, this.onContinueProcessingCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.BeginSubmitResult(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitResult(result, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.EndSubmitResult(System.IAsyncResult result) {
            base.Channel.EndSubmitResult(result);
        }
        
        private System.IAsyncResult OnBeginSubmitResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result = ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase)(inValues[0]));
            return ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).BeginSubmitResult(result, callback, asyncState);
        }
        
        private object[] OnEndSubmitResult(System.IAsyncResult result) {
            ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).EndSubmitResult(result);
            return null;
        }
        
        private void OnSubmitResultCompleted(object state) {
            if ((this.SubmitResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitResultCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitResultAsync(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result) {
            this.SubmitResultAsync(result, null);
        }
        
        public void SubmitResultAsync(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result, object userState) {
            if ((this.onBeginSubmitResultDelegate == null)) {
                this.onBeginSubmitResultDelegate = new BeginOperationDelegate(this.OnBeginSubmitResult);
            }
            if ((this.onEndSubmitResultDelegate == null)) {
                this.onEndSubmitResultDelegate = new EndOperationDelegate(this.OnEndSubmitResult);
            }
            if ((this.onSubmitResultCompletedDelegate == null)) {
                this.onSubmitResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitResultCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitResultDelegate, new object[] {
                        result}, this.onEndSubmitResultDelegate, this.onSubmitResultCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.BeginRawSubmitResult(string jsonResult, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRawSubmitResult(jsonResult, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService.EndRawSubmitResult(System.IAsyncResult result) {
            return base.Channel.EndRawSubmitResult(result);
        }
        
        private System.IAsyncResult OnBeginRawSubmitResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string jsonResult = ((string)(inValues[0]));
            return ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).BeginRawSubmitResult(jsonResult, callback, asyncState);
        }
        
        private object[] OnEndRawSubmitResult(System.IAsyncResult result) {
            bool retVal = ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService)(this)).EndRawSubmitResult(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRawSubmitResultCompleted(object state) {
            if ((this.RawSubmitResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RawSubmitResultCompleted(this, new RawSubmitResultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RawSubmitResultAsync(string jsonResult) {
            this.RawSubmitResultAsync(jsonResult, null);
        }
        
        public void RawSubmitResultAsync(string jsonResult, object userState) {
            if ((this.onBeginRawSubmitResultDelegate == null)) {
                this.onBeginRawSubmitResultDelegate = new BeginOperationDelegate(this.OnBeginRawSubmitResult);
            }
            if ((this.onEndRawSubmitResultDelegate == null)) {
                this.onEndRawSubmitResultDelegate = new EndOperationDelegate(this.OnEndRawSubmitResult);
            }
            if ((this.onRawSubmitResultCompletedDelegate == null)) {
                this.onRawSubmitResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRawSubmitResultCompleted);
            }
            base.InvokeAsync(this.onBeginRawSubmitResultDelegate, new object[] {
                        jsonResult}, this.onEndRawSubmitResultDelegate, this.onRawSubmitResultCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService CreateChannel() {
            return new PhoneAutomationServiceClientChannel(this);
        }
        
        private class PhoneAutomationServiceClientChannel : ChannelBase<WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService>, WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService {
            
            public PhoneAutomationServiceClientChannel(System.ServiceModel.ClientBase<WindowsPhoneTestFramework.Client.AutomationClient.Remote.IPhoneAutomationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetNextCommand(int timeoutInMilliseconds, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = timeoutInMilliseconds;
                System.IAsyncResult _result = base.BeginInvoke("GetNextCommand", _args, callback, asyncState);
                return _result;
            }
            
            public WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase EndGetNextCommand(System.IAsyncResult result) {
                object[] _args = new object[0];
                WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase _result = ((WindowsPhoneTestFramework.Client.AutomationClient.Remote.CommandBase)(base.EndInvoke("GetNextCommand", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginContinueProcessing(System.Guid commandId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = commandId;
                System.IAsyncResult _result = base.BeginInvoke("ContinueProcessing", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndContinueProcessing(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ContinueProcessing", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSubmitResult(WindowsPhoneTestFramework.Client.AutomationClient.Remote.ResultBase result, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = result;
                System.IAsyncResult _result = base.BeginInvoke("SubmitResult", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSubmitResult(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SubmitResult", _args, result);
            }
            
            public System.IAsyncResult BeginRawSubmitResult(string jsonResult, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = jsonResult;
                System.IAsyncResult _result = base.BeginInvoke("RawSubmitResult", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndRawSubmitResult(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("RawSubmitResult", _args, result)));
                return _result;
            }
        }
    }
}
